### ISSUE TITLE
Wiki - Basic Example - Post Processing MATLAB code listing

### ISSUE THREAD

**Issue by mesarcik** [stpaine/FERS#2]
In the matlab listing the variable "sig" is undefined in the one listing.

`[Iin Qin scale] = loadfersHDF5('Monostat.h5');
I_Q_scaled = (Iin + j*Qin)*scale
matched = conv(I_Q_scaled,sig); % perform "matched filtering"
figure(1) %plot output of matched filter
magnitude = sqrt( imag(matched).^2 + real(matched.^2) ); % get magnitude of complex signal
plot(magnitude(length(sig):length(magnitude))) % ignore last bit (overlap of convolution)
hold on`

**Comment by stpaine** [comment]
Corrected
