### ISSUE TITLE
Moving Tx/Rx

### ISSUE THREAD

**Issue by stpaine** [stpaine/FERS#3]
There is a known bug that causes issues with moving transmitters or receivers. 

At present, do not use moving transmitters or receivers, only moving targets.

**Comment by darrynjordan** [comment]
In my experiments, moving monostatic systems seem to simulate correctly.

**Comment by darrynjordan** [comment]
I now use a moving pseudo-monostatic, pulsed configuration, where transmitter and receiver are placed on separate moving platforms, offset from one another. I can add moving and stationary targets.
